name: Deploy worker to Cloudflare

# When to run this action
on:
  push:
    branches:
      - main
  workflow_dispatch:

# GitHub permissions
permissions:
  contents: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "cloudflare-worker"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Run npm install
        run: npm install

      - name: Deploy
        run: npm run worker-deploy